# country_mapping.py

COUNTRY_MAP = {

    # Europe
    "Albanien": "Albania",
    "Andorra": "Andorra",
    "Armenien": "Armenia",
    "Aserbaidschan": "Azerbaijan",
    "Belarus": "Belarus",
    "Belgien": "Belgium",
    "Bosnien und Herzegowina": "Bosnia and Herzegovina",
    "Bulgarien": "Bulgaria",
    "Dänemark": "Denmark",
    "Deutschland": "Germany",
    "England": "England",
    "Estland": "Estonia",
    "Faröer": "Faroe Islands",
    "Finnland": "Finland",
    "Frankreich": "France",
    "Georgien": "Georgia",
    "Gibraltar": "Gibraltar",
    "Griechenland": "Greece",
    "Irland": "Ireland",
    "Island": "Iceland",
    "Italien": "Italy",
    "Kasachstan": "Kazakhstan",
    "Kosovo": "Kosovo",
    "Kroatien": "Croatia",
    "Lettland": "Latvia",
    "Liechtenstein": "Liechtenstein",
    "Litauen": "Lithuania",
    "Luxemburg": "Luxembourg",
    "Malta": "Malta",
    "Moldau": "Moldova",
    "Montenegro": "Montenegro",
    "Niederlande": "Netherlands",
    "Nordirland": "Northern Ireland",
    "Nordmazedonien": "North Macedonia",
    "Norwegen": "Norway",
    "Österreich": "Austria",
    "Polen": "Poland",
    "Portugal": "Portugal",
    "Rumänien": "Romania",
    "Russland": "Russia",
    "San Marino": "San Marino",
    "Schottland": "Scotland",
    "Schweden": "Sweden",
    "Schweiz": "Switzerland",
    "Serbien": "Serbia",
    "Slowakei": "Slovakia",
    "Slowenien": "Slovenia",
    "Spanien": "Spain",
    "Tschechien": "Czech Republic",
    "Türkei": "Turkey",
    "Ukraine": "Ukraine",
    "Ungarn": "Hungary",
    "Wales": "Wales",
    "Zypern": "Cyprus",

    # South America
    "Argentinien": "Argentina",
    "Bolivien": "Bolivia",
    "Brasilien": "Brazil",
    "Chile": "Chile",
    "Ecuador": "Ecuador",
    "Kolumbien": "Colombia",
    "Paraguay": "Paraguay",
    "Peru": "Peru",
    "Uruguay": "Uruguay",
    "Venezuela": "Venezuela",

    # North America
    "Kanada": "Canada",
    "Costa Rica": "Costa Rica",
    "Dominikanische Republik": "Dominican Republic",
    "El Salvador": "El Salvador",
    "Guatemala": "Guatemala",
    "Honduras": "Honduras",
    "Jamaika": "Jamaica",
    "Mexiko": "Mexico",
    "Nicaragua": "Nicaragua",
    "Panama": "Panama",
    "USA": "United States",
    "Vereinigte Staaten": "United States",
    "Trinidad und Tobago": "Trinidad and Tobago",
    "Belize": "Belize",

    # Africa
    "Algerien": "Algeria",
    "Ägypten": "Egypt",
    "Äthiopien": "Ethiopia",
    "Benin": "Benin",
    "Botswana": "Botswana",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Elfenbeinküste": "Ivory Coast",
    "Gabun": "Gabon",
    "Gambia": "Gambia",
    "Ghana": "Ghana",
    "Guinea": "Guinea",
    "Kamerun": "Cameroon",
    "Kenia": "Kenya",
    "Libyen": "Libya",
    "Madagaskar": "Madagascar",
    "Malawi": "Malawi",
    "Mali": "Mali",
    "Marokko": "Morocco",
    "Mauretanien": "Mauritania",
    "Mosambik": "Mozambique",
    "Namibia": "Namibia",
    "Niger": "Niger",
    "Nigeria": "Nigeria",
    "Ruanda": "Rwanda",
    "Sambia": "Zambia",
    "Senegal": "Senegal",
    "Simbabwe": "Zimbabwe",
    "Südafrika": "South Africa",
    "Sudan": "Sudan",
    "Tansania": "Tanzania",
    "Togo": "Togo",
    "Tunesien": "Tunisia",
    "Uganda": "Uganda",

    # Asia
    "Afghanistan": "Afghanistan",
    "Bangladesch": "Bangladesh",
    "Brunei": "Brunei",
    "China": "China",
    "Hongkong": "Hong Kong",
    "Indien": "India",
    "Indonesien": "Indonesia",
    "Irak": "Iraq",
    "Iran": "Iran",
    "Israel": "Israel",
    "Japan": "Japan",
    "Jordanien": "Jordan",
    "Kambodscha": "Cambodia",
    "Kirgisistan": "Kyrgyzstan",
    "Laos": "Laos",
    "Libanon": "Lebanon",
    "Malaysia": "Malaysia",
    "Malediven": "Maldives",
    "Mongolei": "Mongolia",
    "Myanmar": "Myanmar",
    "Nepal": "Nepal",
    "Oman": "Oman",
    "Pakistan": "Pakistan",
    "Palästina": "Palestine",
    "Philippinen": "Philippines",
    "Katar": "Qatar",
    "Saudi-Arabien": "Saudi Arabia",
    "Singapur": "Singapore",
    "Südkorea": "South Korea",
    "Syrien": "Syria",
    "Taiwan": "Taiwan",
    "Tadschikistan": "Tajikistan",
    "Thailand": "Thailand",
    "Timor-Leste": "Timor-Leste",
    "Turkmenistan": "Turkmenistan",
    "Usbekistan": "Uzbekistan",
    "Vereinigte Arabische Emirate": "United Arab Emirates",
    "Vietnam": "Vietnam",

    # Oceania
    "Australien": "Australia",
    "Fidschi": "Fiji",
    "Neuseeland": "New Zealand",
    "Papua-Neuguinea": "Papua New Guinea",
    "Salomonen": "Solomon Islands",
    "Vanuatu": "Vanuatu",

}
